version: '3.1'

services:
  app_flask:
   build: .
   ports:
     - 5000:5000
   volumes:
    - flask_v
   networks:
    - flask_network
  redis:
    image: redis
    networks:
      - flask_network 

volumes:
   flask_v:

networks:
  flask_network: